#!/usr/bin/env python3
"""Build docs/rules/RULES.md: every rule agents in Brian's workspace are expected to follow.

Reads the AES rules register (docs/rules/register.yaml) and, read-only, project-meta's legacy
policy register (policy/registry.yaml), and writes one Markdown page a person can scan:
what each rule says, how it is enforced, and where its evidence is.

    python scripts/rules/build_rules_page.py            # rewrite the page
    python scripts/rules/build_rules_page.py --check    # exit 1 if the page is out of date
"""
from __future__ import annotations

import argparse
import os
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
REGISTER = ROOT / "docs" / "rules" / "register.yaml"
OUTPUT = ROOT / "docs" / "rules" / "RULES.md"
LEGACY = Path(os.environ.get("PROJECT_META", Path.home() / "code" / "project-meta")) / "policy" / "registry.yaml"

STATUS_ORDER = ["enforced", "partially-enforced", "checked", "advisory", "planned", "licensed", "withdrawn"]
ORIGIN_TITLES = {
    "workspace-instructions": "Rules in the workspace instructions",
    "feedback-loop": "Rules from the feedback loop",
}
ORIGIN_INTROS = {
    "workspace-instructions": (
        "The named rules in the instruction file every Claude Code and Codex session loads "
        "(projects-dotclaude `AGENTS.md`). That file also holds unnamed rules (merging, privacy, storage, "
        "closeout format); read it in full for those."
    ),
    "feedback-loop": (
        "Rules the feedback loop derived from recorded evidence. *Licensed* means the loop found enough "
        "independent sightings and handed the rule to agents to adopt; *enforced* means an agent adopted it as a "
        "check that refuses the violation."
    ),
}


def _cell(text: Any, limit: int | None = None) -> str:
    """One Markdown table cell: single line, pipes escaped, optionally shortened at a word boundary."""
    s = " ".join(str(text or "").split()).replace("|", "\\|")
    if limit and len(s) > limit:
        s = s[: limit].rsplit(" ", 1)[0] + " …"
    return s


def _status_counts(rules: list[dict[str, Any]]) -> str:
    c = Counter(r.get("enforcement_status", "unstated") for r in rules)
    order = [s for s in STATUS_ORDER if s in c] + sorted(s for s in c if s not in STATUS_ORDER)
    return ", ".join(f"{c[s]} {s}" for s in order)


def _evidence(rule: dict[str, Any]) -> str:
    ev = rule.get("evidence") or {}
    links = []
    if ev.get("concern"):
        links.append(f"[issue #{ev['concern'].rsplit('/', 1)[-1]}]({ev['concern']})")
    if ev.get("problem"):
        links.append(f"[problem]({ev['problem']})")
    if ev.get("sightings"):
        links.append(f"{ev['sightings']} sightings")
    if ev.get("adopted_from"):
        links.append("adopted from " + ", ".join(ev["adopted_from"]))
    return "; ".join(links)


def render(register: dict[str, Any], legacy: dict[str, Any] | None, legacy_path: str) -> str:
    rules = register["rules"]
    statuses = register.get("enforcement_statuses", {})
    lines = [
        "# Rules agents follow",
        "",
        "Every rule agents in Brian's workspace are expected to follow, how each one is enforced, and where its "
        "evidence is. Generated by `scripts/rules/build_rules_page.py` from [the AES rules register](register.yaml) "
        "and, read-only, project-meta's legacy register; edit the register, not this page.",
        "",
        "| Section | Rules | How they are enforced |",
        "| --- | --- | --- |",
    ]
    by_origin: dict[str, list[dict[str, Any]]] = {}
    for r in rules:
        by_origin.setdefault(r["origin"], []).append(r)
    for origin, rs in by_origin.items():
        title = ORIGIN_TITLES.get(origin, origin)
        anchor = title.lower().replace(" ", "-")
        lines.append(f"| [{title}](#{anchor}) | {len(rs)} | {_status_counts(rs)} |")
    legacy_rules = (legacy or {}).get("policies") or []
    if legacy_rules:
        lines.append(f"| [Legacy project-meta register](#legacy-project-meta-register) | {len(legacy_rules)} | "
                     f"{_status_counts(legacy_rules)} |")
    lines += ["", "What the statuses mean: " + "; ".join(f"**{k}**: {v}" for k, v in statuses.items()) + ".", ""]

    for origin, rs in by_origin.items():
        lines += [f"## {ORIGIN_TITLES.get(origin, origin)}", "", ORIGIN_INTROS.get(origin, ""), ""]
        rs = sorted(rs, key=lambda r: (STATUS_ORDER.index(r["enforcement_status"])
                                       if r["enforcement_status"] in STATUS_ORDER else 99, r["id"]))
        if origin == "feedback-loop":
            lines += ["| Rule | Status | How it is enforced | Evidence |", "| --- | --- | --- | --- |"]
            for r in rs:
                lines.append(f"| **{_cell(r['id'])}**: {_cell(r['rule'])} | {_cell(r['enforcement_status'])} | "
                             f"{_cell(r['enforcement_mechanism'])} | {_evidence(r)} |")
        else:
            lines += ["| Rule | Status | How it is enforced |", "| --- | --- | --- |"]
            for r in rs:
                lines.append(f"| **{_cell(r['id'])}**: {_cell(r['rule'])} | {_cell(r['enforcement_status'])} | "
                             f"{_cell(r['enforcement_mechanism'])} |")
        lines.append("")

    lines += ["## Legacy project-meta register", ""]
    if not legacy_rules:
        lines += [f"Not available when this page was built (`{legacy_path}` could not be read).", ""]
    else:
        lines += [
            f"project-meta's {len(legacy_rules)} rules, shown read-only from `{legacy_path}`. They are legacy: a rule "
            "moves into the AES register only when the feedback loop gathers evidence for it or retires it. The "
            "advisory ones (nothing checks them) are where that starts.",
            "",
        ]
        groups: dict[str, list[dict[str, Any]]] = {}
        for p in legacy_rules:
            groups.setdefault(p.get("enforcement_status") or "unstated", []).append(p)
        for status in [s for s in STATUS_ORDER if s in groups] + sorted(s for s in groups if s not in STATUS_ORDER):
            ps = sorted(groups[status], key=lambda p: p["id"])
            lines += [f"<details><summary><strong>{status}</strong> ({len(ps)})</summary>", "",
                      "| Rule | How it is enforced |", "| --- | --- |"]
            for p in ps:
                lines.append(f"| **{_cell(p['id'])}**: {_cell(p.get('policy'), 220)} | "
                             f"{_cell(p.get('enforcement_mechanism'), 180)} |")
            lines += ["", "</details>", ""]
    return "\n".join(lines).rstrip() + "\n"


def build(register_path: Path = REGISTER, legacy_path: Path = LEGACY) -> str:
    register = yaml.safe_load(register_path.read_text(encoding="utf-8"))
    if register.get("schema_version") != "aes-rules-register/v1":
        raise SystemExit(f"{register_path}: unexpected schema_version {register.get('schema_version')!r}")
    try:
        legacy = yaml.safe_load(legacy_path.read_text(encoding="utf-8"))
    except OSError:
        legacy = None
    shown = "project-meta/policy/registry.yaml" if legacy_path == LEGACY else str(legacy_path)
    return render(register, legacy, shown)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--register", type=Path, default=REGISTER)
    parser.add_argument("--legacy", type=Path, default=LEGACY)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true", help="exit 1 if the page differs from a fresh build")
    args = parser.parse_args()
    page = build(args.register, args.legacy)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        ok = current == page
        print(f"rules page {'up to date' if ok else 'OUT OF DATE'}: {args.output} (exit {0 if ok else 1})")
        return 0 if ok else 1
    args.output.write_text(page, encoding="utf-8")
    print(f"wrote {args.output} ({page.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
