#!/usr/bin/env python3
"""Wire the AES commit rule (`aes commit check`) into every repository under a workspace.

Plan proposals/aes-planning, work units P4 and P6; Brian, 2026-10-07: "go" on rolling the
rule out to all work in observe mode, then enforcing after two days where the replay's
false refusals are at or under 1 in 5.

Git runs a hook from exactly one directory, so there are three kinds of repository:

- global: no local ``core.hooksPath``; Git uses ``~/.config/git/hooks``. The installer adds
  one call to the generated ``_aes_commit_rule.sh`` at the top of the global ``commit-msg``.
- local: a local ``core.hooksPath`` (the governed repositories' tracked ``hooks/``). The
  installer points that setting at a generated wrapper folder,
  ``~/.config/git/hooks-local/<repo>/``, whose ``commit-msg`` runs the rule and then the
  repository's own hook, and whose other hooks run the repository's own hook unchanged. The
  original value is kept in ``aes.originalHooksPath`` so ``uninstall`` restores it.
- aes: the repository's hooks are already generated by ``aes hooks install`` and run the rule.

The rule's mode comes from the repository's ``.aes/commit_rule.yaml`` or, when there is
none, the machine-wide ``~/.config/aes/commit_rule.yaml`` (observe unless it says enforce).
``check`` reports every repository's wiring and exits non-zero when any is unwired, so a
daily run can say when the control has gone dark somewhere.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import subprocess
import sys
from pathlib import Path

HOME = Path.home()
GLOBAL_HOOKS = HOME / ".config" / "git" / "hooks"
LOCAL_WRAPPERS = HOME / ".config" / "git" / "hooks-local"
MACHINE_CONFIG = HOME / ".config" / "aes" / "commit_rule.yaml"
SNIPPET = GLOBAL_HOOKS / "_aes_commit_rule.sh"
CALL_LINE = '. "$(dirname "$0")/_aes_commit_rule.sh" && aes_commit_rule "$1" || exit $?'
AES_MARK = "managed by aes hooks install"
HOOK_NAMES = (
    "applypatch-msg", "pre-applypatch", "post-applypatch", "pre-commit", "pre-merge-commit",
    "prepare-commit-msg", "commit-msg", "post-commit", "pre-rebase", "post-checkout", "post-merge",
    "pre-push", "pre-auto-gc", "post-rewrite", "reference-transaction", "push-to-checkout",
)

SNIPPET_TEXT = """#!/bin/sh
# Generated by agentic-engineering-system-canonical proposals/aes-planning/rollout/install_everywhere.py.
# Runs the AES commit rule on the message git is about to record. In observe mode it only logs;
# in enforce mode a refusal stops the commit. Edits here are overwritten by the installer.
aes_commit_rule() {
  top=$(git rev-parse --show-toplevel 2>/dev/null) || return 0
  if ! command -v aes >/dev/null 2>&1; then
    echo "commit-msg: WARNING: 'aes' is not installed, so the AES commit rule did not run." >&2
    mkdir -p "$HOME/.local/state/aes" && \\
      printf '%s rule-not-run no-aes %s\\n' "$(date -u +%FT%TZ)" "$top" >> "$HOME/.local/state/aes/commit-rule-missing.log"
    return 0
  fi
  aes commit check --root "$top" "$1"
}
"""

LOCAL_COMMIT_MSG = """#!/bin/sh
# Generated by install_everywhere.py: AES commit rule, then this repository's own commit-msg hook.
. "{snippet}" && aes_commit_rule "$1" || exit $?
top=$(git rev-parse --show-toplevel)
orig="{orig}/commit-msg"
[ -x "$orig" ] || exit 0
exec "$orig" "$@"
"""

LOCAL_PASS = """#!/bin/sh
# Generated by install_everywhere.py: runs this repository's own {name} hook unchanged.
top=$(git rev-parse --show-toplevel)
orig="{orig}/{name}"
[ -x "$orig" ] || exit 0
exec "$orig" "$@"
"""


def git(repo: Path, *args: str, check: bool = False) -> str:
    done = subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, check=False)
    if check and done.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} in {repo}: {done.stderr.strip()}")
    return done.stdout.strip()


def repositories(workspace: Path) -> list[Path]:
    return sorted(p for p in workspace.iterdir() if p.is_dir() and (p / ".git").exists())


def repo_id(repo: Path) -> str:
    """The underlying repository's name: linked worktrees share one config, so they share one wrapper folder."""
    common = git(repo, "rev-parse", "--path-format=absolute", "--git-common-dir")
    return Path(common).parent.name if common else repo.name


def _hooks_dir(repo: Path, path: str) -> Path:
    return Path(path) if Path(path).is_absolute() else repo / path


def is_aes_native(repo: Path) -> bool:
    """An AES project whose own hooks (``aes hooks install`` into .githooks) already run the rule."""
    original = git(repo, "config", "--local", "aes.originalHooksPath") or git(repo, "config", "--local", "core.hooksPath")
    return (repo / ".aes" / "project.yaml").is_file() and original == ".githooks"


def kind(repo: Path) -> tuple[str, str]:
    """(kind, local hooksPath or '')."""
    local = git(repo, "config", "--local", "core.hooksPath")
    if is_aes_native(repo):
        return "aes", local
    if not local or _hooks_dir(repo, local).resolve() == GLOBAL_HOOKS.resolve():
        return "global", local
    if Path(local).is_absolute() and Path(local).resolve() == (LOCAL_WRAPPERS / repo_id(repo)).resolve():
        return "local", local
    hook = _hooks_dir(repo, local) / "commit-msg"
    if hook.is_file() and AES_MARK in hook.read_text(encoding="utf-8", errors="replace"):
        return "aes", local
    return "local", local


def _write_exec(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def install_global() -> str:
    _write_exec(SNIPPET, SNIPPET_TEXT)
    hook = GLOBAL_HOOKS / "commit-msg"
    text = hook.read_text(encoding="utf-8")
    if CALL_LINE in text:
        return "global commit-msg already calls the rule"
    backup = hook.with_name("commit-msg.before-aes")
    if not backup.exists():
        shutil.copy2(hook, backup)
    lines = text.splitlines()
    at = next((i for i, line in enumerate(lines) if line.startswith(". ") or "chain_to_repo_hook" in line), len(lines))
    lines.insert(at, CALL_LINE)
    hook.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return f"global commit-msg now calls the rule (original kept at {backup})"


def install_local(repo: Path) -> str:
    current = git(repo, "config", "--local", "core.hooksPath")
    wrappers = LOCAL_WRAPPERS / repo_id(repo)
    original = git(repo, "config", "--local", "aes.originalHooksPath") or current
    if not git(repo, "config", "--local", "aes.originalHooksPath"):
        git(repo, "config", "--local", "aes.originalHooksPath", original, check=True)
    source = _hooks_dir(repo, original)
    names = {p.name for p in source.iterdir() if p.is_file() and os.access(p, os.X_OK)} if source.is_dir() else set()
    # a relative path resolves against each worktree's top; an absolute one is used as is
    orig_ref = original if Path(original).is_absolute() else f"$top/{original}"
    names = (names & set(HOOK_NAMES)) | {"commit-msg"}
    if wrappers.exists():
        shutil.rmtree(wrappers)
    for name in sorted(names):
        text = (LOCAL_COMMIT_MSG.format(snippet=SNIPPET, orig=orig_ref) if name == "commit-msg"
                else LOCAL_PASS.format(name=name, orig=orig_ref))
        _write_exec(wrappers / name, text)
    git(repo, "config", "--local", "core.hooksPath", str(wrappers), check=True)
    return f"{repo.name}: hooks now run through {wrappers} ({', '.join(sorted(names))}); original {original}"


def uninstall_local(repo: Path) -> str:
    original = git(repo, "config", "--local", "aes.originalHooksPath")
    if not original:
        return f"{repo.name}: nothing to undo"
    git(repo, "config", "--local", "core.hooksPath", original, check=True)
    git(repo, "config", "--local", "--unset", "aes.originalHooksPath")
    shutil.rmtree(LOCAL_WRAPPERS / repo_id(repo), ignore_errors=True)
    return f"{repo.name}: hooksPath restored to {original}"


def wired(repo: Path) -> tuple[str, bool, str]:
    k, local = kind(repo)
    if k == "aes":
        return k, True, f"AES-generated hooks at {local}"
    if k == "global":
        hook = GLOBAL_HOOKS / "commit-msg"
        ok = SNIPPET.is_file() and hook.is_file() and CALL_LINE in hook.read_text(encoding="utf-8")
        return k, ok, "global commit-msg calls the rule" if ok else "global commit-msg does not call the rule"
    hook = LOCAL_WRAPPERS / repo_id(repo) / "commit-msg"
    ok = local == str(LOCAL_WRAPPERS / repo_id(repo)) and hook.is_file() and "aes_commit_rule" in hook.read_text(encoding="utf-8")
    return k, ok, f"hooksPath={local}" + ("" if ok else " (not wired)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("action", choices=["install", "check", "uninstall"])
    ap.add_argument("--workspace", type=Path, default=HOME / "code")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()
    repos = repositories(args.workspace)
    if args.action == "install":
        if not shutil.which("aes"):
            print("install: 'aes' is not on PATH; install it first (uv tool install --from <AES checkout> agentic-engineering-system)", file=sys.stderr)
            return 2
        if not MACHINE_CONFIG.exists():
            MACHINE_CONFIG.parent.mkdir(parents=True, exist_ok=True)
            MACHINE_CONFIG.write_text("# AES commit rule, machine-wide default for repositories without .aes/commit_rule.yaml.\n"
                                      "# observe: log only; enforce: refuse. Per-repository overrides go under repos: {<dir name>: {mode: ...}}.\n"
                                      "mode: observe\nrepos: {}\n", encoding="utf-8")
        print(install_global())
        failures = 0
        for repo in repos:
            if is_aes_native(repo) and git(repo, "config", "--local", "aes.originalHooksPath"):
                print(uninstall_local(repo) + " (AES project: its own hooks run the rule)")
                continue
            if kind(repo)[0] == "local":
                try:
                    print(install_local(repo))
                except (RuntimeError, OSError) as exc:
                    failures += 1
                    print(f"FAILED {repo.name}: {exc}", file=sys.stderr)
        print(f"install: {len(repos)} repositories, {failures} failed")
        return 1 if failures else 0
    if args.action == "uninstall":
        for repo in repos:
            print(uninstall_local(repo))
        backup = GLOBAL_HOOKS / "commit-msg.before-aes"
        if backup.exists():
            shutil.copy2(backup, GLOBAL_HOOKS / "commit-msg")
            print("global commit-msg restored")
        return 0
    rows = [(repo.name, *wired(repo)) for repo in repos]
    unwired = [r for r in rows if not r[2]]
    runtime = shutil.which("aes")
    if args.json:
        print(json.dumps({"runtime": runtime, "machine_config": str(MACHINE_CONFIG) if MACHINE_CONFIG.exists() else None,
                          "repositories": [{"repo": n, "kind": k, "wired": w, "detail": d} for n, k, w, d in rows]}, indent=1))
    else:
        for name, k, ok, detail in rows:
            if not ok:
                print(f"UNWIRED {name} ({k}): {detail}")
    counts = {k: sum(1 for r in rows if r[1] == k) for k in ("global", "local", "aes")}
    print(f"check: {len(rows)} repositories ({counts['global']} global, {counts['local']} local, {counts['aes']} aes); "
          f"{len(rows) - len(unwired)} wired, {len(unwired)} unwired; runtime {'at ' + runtime if runtime else 'MISSING'}")
    return 1 if unwired or not runtime else 0


if __name__ == "__main__":
    raise SystemExit(main())
