// A bounded projection over the retained trace; it does not adopt policy.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
const dir=dirname(fileURLToPath(import.meta.url));
const observed=JSON.parse(await readFile(join(dir,'probe-output.json'),'utf8'));
const project=process.argv[2];
if(!project||observed.counts.failed||observed.exit_status!==0)throw new Error('Require checkout and passing diagnosis');
const source=(path,needle)=>{
 const pin=observed.subject.sources.find(s=>s.path===path);
 const text=execFileSync('git',['-C',project,'show',pin.revision+':'+path],{encoding:'utf8'});
 const line=text.split('\n').findIndex(s=>s.includes(needle))+1;
 if(!line)throw new Error('Source marker absent: '+needle);
 return {...pin,line,url:'https://github.com/'+observed.subject.repository+'/blob/'+pin.revision+'/'+path+'#L'+line};
};
const sources={contract:source('scripts/control_triggers.py','``clear``'),index:source('scripts/hook_receipt_index.py','def refresh_and_load'),reader:source('scripts/control_triggers.py','def hook_latency_p90'),mapping:source('scripts/control_triggers.py','def enforced_without_receipts'),report:source('scripts/control_triggers.py','def main'),route:source('scripts/control_triggers.py','def route'),entrypoint:source('scripts/policy_system_status.py','if "--triggers"'),audit:source('scripts/run_local_daily_audit.sh','[3h/11] Evaluating control review triggers')};
const stages=[
 {id:'meaning',modelRef:'definitions',title:'Define what “clear” means',state:'working',mark:'Contract verified',summary:'The source was read; the trigger did not fire.',detail:'The owning check explicitly distinguishes clear from unknown. This step verifies a source contract, rather than proving that every agent received the rule.',sourceIds:['contract']},
 {id:'execution',modelRef:'action',title:'Run hooks and leave evidence',state:'unknown',mark:'Live execution untested',summary:'Whether the live hooks ran is outside this test.',detail:'Temporary observation folders stand in for the receipt store. The test does not establish which live hooks executed, whether they obeyed policy, or whether a real historical issue was closed.',sourceIds:[]},
 {id:'coverage',modelRef:'observations',title:'Read the available evidence',state:'working',mark:'Executed in isolation',summary:'1 session exists; 0 fully read. Coverage is partial.',detail:'The real index refresh ran against a temporary session folder with a zero-second scan budget. It reported budget_exhausted=true and no rows. Uncertainty is present before the check assigns its status.',sourceIds:['index']},
 {id:'classification',modelRef:'control',title:'Turn evidence into a status',state:'broken',mark:'Root break reproduced',summary:'Partial evidence becomes “clear”.',detail:'The latency reader returns clear with partial coverage and either no samples or one fast sample. Another reader returns clear for an unmapped required control even with complete coverage. Coverage and mapping warnings remain in prose, but do not constrain the status.',sourceIds:['reader','mapping']},
 {id:'reporting',modelRef:'evidence_record',title:'Write the result for consumers',state:'working',mark:'Executed in isolation',summary:'The report says clear and the command exits 0.',detail:'The real CLI wrote clear into its report. Its successful exit means the command completed; it does not establish complete coverage or control health. The daily audit reaches this CLI through policy_system_status --triggers; live scheduling was not exercised.',sourceIds:['report','entrypoint','audit']},
 {id:'closure',modelRef:'concerns',title:'Decide whether to close the concern',state:'broken',mark:'Consequence reproduced',summary:'The router asks to close the fixture concern.',detail:'The real router called close_concern for trigger:hook-latency-p90. An isolated in-memory issue adapter retained that attempted action; no GitHub issue was closed by the probe. With unknown, the same router performs no close. Positive slow evidence still opens a concern.',sourceIds:['route']}
];
const trace={schema:'ecosystem-failure-trace/v1',question:'Where does missing evidence become a clear result?',observedAt:observed.observed_at,subject:observed.subject,boundary:observed.boundary,stages,sources,links:stages.slice(1).map((s,i)=>({from:stages[i].id,to:s.id})),modelRevision:'6145a13a1f43163d423c175a28a8fc40b17d6126',recommendation:'Repair the check that assigns status: unresolved coverage or mapping must not justify clear. Preserve positive fired evidence. The existing unknown route already leaves concerns open.',issue:'https://github.com/BrianMills2718/project-meta/issues/2412',counts:observed.counts,cases:observed.cases,repairState:'Not implemented by this modeling step'};
await writeFile(join(dir,'trace.json'),JSON.stringify(trace,null,2)+'\n');
const payload=JSON.stringify(trace).replaceAll('<','\\u003c').replaceAll('>','\\u003e');
const html=String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Why missing evidence can close a concern</title><style>
:root{--ink:#172536;--muted:#52647a;--line:#cdd7e2;--blue:#235e9b;--green:#17634d;--red:#942c2c;--paper:#f6f7fa;--panel:#fff}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.45 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:24px}h1{font-size:30px;line-height:1.16;margin:14px 0 8px}h2{font-size:23px;line-height:1.2;margin:0 0 12px}p{margin:0 0 12px}.muted{color:var(--muted);font-size:14px}.boundary{padding:10px 14px;background:#edf2f7;border-left:3px solid var(--blue);margin:16px 0}.workspace{display:grid;grid-template-columns:minmax(350px,1fr) minmax(360px,1fr);gap:24px;align-items:start}.flow{list-style:none;margin:0;padding:0}.flow li+li:before{content:'↓';display:block;text-align:center;font-size:21px;line-height:23px;color:var(--muted)}.stage{display:grid;grid-template-columns:28px 1fr;gap:10px;width:100%;text-align:left;border:1px solid var(--line);border-radius:8px;background:var(--panel);padding:11px 14px;font:inherit;color:inherit;cursor:pointer}.stage strong{display:block;font-size:16px;line-height:1.3}.stage small{display:block;font-size:13px;color:var(--muted);margin-top:2px}.state{display:block;font-size:12px;font-weight:650;margin-top:5px}.working .state{color:var(--green)}.unknown .state{color:var(--muted)}.broken .state{color:var(--red)}.stage[data-stage=classification]{border-left:5px solid var(--red);background:#fff1ef}.stage[aria-pressed=true]{outline:2px solid var(--blue);outline-offset:2px}.number{font-size:13px;color:var(--muted);padding-top:3px}.detail{position:sticky;top:18px;border:1px solid var(--line);border-radius:10px;background:var(--panel);padding:22px}.detail h3{font-size:14px;margin:20px 0 8px}.detail p{font-size:15px}.badge{display:inline-block;border:1px solid var(--line);padding:4px 8px;border-radius:15px;font-size:12px;margin-bottom:12px}.recommendation{border-top:1px solid var(--line);padding-top:18px;margin-top:20px}a{color:var(--blue);text-underline-offset:3px}.source{display:block;margin:12px 0;overflow-wrap:anywhere;font-size:13px}.source small{display:block;color:var(--muted)}button:focus-visible,a:focus-visible{outline:3px solid var(--blue);outline-offset:4px}.foot{font-size:12px;color:var(--muted);margin-top:20px}#tooltip{position:fixed;z-index:999;background:var(--ink);color:white;border-radius:7px;padding:9px 12px;max-width:310px;font-size:12px;pointer-events:none;box-shadow:0 5px 18px #0002}#tooltip[hidden]{display:none}.links{display:flex;gap:18px;flex-wrap:wrap;margin-top:18px}.legend{font-size:12px;color:var(--muted);margin:10px 0 16px}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:780px){main{padding:16px}.workspace{grid-template-columns:minmax(0,1fr)}.detail{position:static}h1{font-size:27px}.stage{min-height:84px}}
</style></head><body><main><a href="../index.html" data-help="Return to the complete policy-system model and its four architecture views.">← Whole system model</a><h1>Why missing evidence can close a concern</h1><p>The reader knows its evidence is incomplete. The check turns that uncertainty into “clear”.</p><div class="boundary"><strong>Diagnosis, not a repair.</strong> Real index, check, command and router; temporary evidence and an isolated issue adapter. No real concern was closed.</div><p class="legend">Working: verified contract or isolated execution · Broken: reproduced violation · Unknown: outside this test</p><div class="workspace"><ol class="flow" id="flow" aria-label="Evidence-to-correction flow"></ol><aside class="detail" id="detail" aria-live="polite"></aside></div><div class="links"><a href="probe-output.json" data-help="Read the retained execution evidence, cases, exact subject and eight diagnosis checks.">Executed evidence</a><a href="trace.json" data-help="Read the semantic trace, model bindings, source pins and explicit tested boundary.">Trace data</a><a href="https://github.com/BrianMills2718/project-meta/issues/2412" data-help="Open the owning concern for repair and verification against this failure.">Owning concern</a></div><p class="foot" id="foot"></p><span class="sr" id="announcement" aria-live="polite"></span></main><div id="tooltip" role="tooltip" hidden></div><script type="application/json" id="trace-data">__TRACE__</script><script>
const trace=JSON.parse(document.querySelector('#trace-data').textContent),$=s=>document.querySelector(s),label={working:'Working',broken:'Broken',unknown:'Unknown'};
function add(parent,tag,text,className){const e=document.createElement(tag);e.textContent=text;if(className)e.className=className;parent.appendChild(e);return e;}
function select(id){const s=trace.stages.find(s=>s.id===id);if(!s)return;for(const b of document.querySelectorAll('.stage'))b.setAttribute('aria-pressed',String(b.dataset.stage===id));const p=$('#detail');p.replaceChildren();add(p,'span',label[s.state]+' · '+s.mark,'badge');add(p,'h2',s.title);add(p,'p',s.detail);add(p,'h3','Part of the system model');add(p,'p',({definitions:'Policy definition',action:'Agent action',observations:'Observation',control:'Guidance and checks',evidence_record:'Native evidence',concerns:'Owned concern'})[s.modelRef]);if(s.sourceIds.length){add(p,'h3','Exact source');for(const id of s.sourceIds){const pin=trace.sources[id],a=add(p,'a',pin.path,'source');a.href=pin.url;a.target='_blank';a.rel='noopener';a.dataset.help='Open this exact source at line '+pin.line+' of commit '+pin.revision.slice(0,8)+'.';add(a,'small',pin.revision.slice(0,8)+' · line '+pin.line);}}else add(p,'p','Live hook execution was not verified.','muted');const next=add(p,'section','','recommendation');add(next,'h3','Where the repair belongs');add(next,'p',trace.recommendation);add(next,'p','Repair state: '+trace.repairState+'.','muted');$('#announcement').textContent=s.title+': '+label[s.state];}
for(const [i,s] of trace.stages.entries()){const li=add($('#flow'),'li',''),b=add(li,'button','','stage '+s.state);b.type='button';b.dataset.stage=s.id;b.dataset.help=s.title+': '+label[s.state]+'. Select to inspect the tested boundary and pinned evidence.';b.setAttribute('aria-pressed','false');add(b,'span',String(i+1),'number');const words=add(b,'span','');add(words,'strong',s.title);add(words,'small',s.summary);add(words,'span',label[s.state]+' · '+s.mark,'state');b.onclick=()=>{select(s.id);if(innerWidth<781)$('#detail').scrollIntoView({behavior:'smooth',block:'start'});};}
$('#foot').textContent=trace.counts.passed+' diagnosis checks passed; '+trace.counts.failed+' failed. Passing reproduces the defects. Project Meta '+trace.subject.revision.slice(0,8)+' · '+new Date(trace.observedAt).toLocaleString()+'. Read-only snapshot; live historical closure is unknown.';
const tip=$('#tooltip');let timer;function hide(){clearTimeout(timer);tip.hidden=true;}function show(target,delay=100){clearTimeout(timer);timer=setTimeout(()=>{tip.textContent=target.dataset.help;tip.hidden=false;const r=target.getBoundingClientRect(),b=tip.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(innerWidth-b.width-8,r.left))+'px';tip.style.top=Math.max(8,Math.min(innerHeight-b.height-8,r.bottom+7))+'px';},delay);}document.addEventListener('pointerover',e=>{const t=e.target.closest('[data-help]');if(t)show(t);});document.addEventListener('pointerout',e=>{const t=e.target.closest('[data-help]');if(t&&!t.contains(e.relatedTarget))hide();});document.addEventListener('focusin',e=>{const t=e.target.closest('[data-help]');if(t)show(t);});document.addEventListener('focusout',hide);document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){const t=e.target.closest('[data-help]');if(t){show(t,0);setTimeout(hide,2800);}}});document.addEventListener('keydown',e=>{if(e.key==='Escape')hide();});select('classification');
</script></body></html>`;
await writeFile(join(dir,'index.html'),html.replace('__TRACE__',payload));
console.log(JSON.stringify({passed:3,failed:0,errored:0,skipped:0,exit_status:0,stages:stages.length,sourceBindings:Object.keys(sources).length}));
